# Generated by Django 4.2.2 on 2023-06-28 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0002_task_remove_tarea_usuario_delete_etiqueta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='label',
            field=models.CharField(choices=[('A', 'Alta'), ('M', 'Media'), ('B', 'Baja')], max_length=2),
        ),
    ]
